### ISSUE TITLE
Install fails on FreeBSD [x86_64-freebsd9.0]

### ISSUE THREAD

**Issue by kiwicustom** [tmm1/rbtrace#22]
[discourse@nginx ~/public_html/beta]$ ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-freebsd9.0]

---
same result for:
 1) gem install rbtrace -v '0.4.1'
 2) gem install rbtrace -v '0.n.n'
 3) gem install rbtrace

EXAMPLE

[discourse@nginx ~/public_html/beta]$ gem install rbtrace -v '0.4.1'
Building native extensions.  This could take a while...
ERROR:  Error installing rbtrace:
        ERROR: Failed to build gem native extension.

    /home/discourse/.rvm/rubies/ruby-2.0.0-p247/bin/ruby extconf.rb
  -- tar zxvf msgpack-0.5.7.tar.gz
  -- ./configure --disable-dependency-tracking --disable-shared --with-pic --prefix=/usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/
  -- make install
checking for main() in -lmsgpackc_ext... yes
checking for msgpack.h... yes
checking for rb_during_gc() in ruby.h... yes
checking for rb_gc_add_event_hook() in ruby.h,node.h... no
creating Makefile

make "DESTDIR="
compiling rbtrace.c
In file included from /usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack/object.h:21,
                 from /usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack.h:23,
                 from rbtrace.c:23:
/usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack/zone.h: In function 'msgpack_zone_malloc_no_align':
/usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack/zone.h:99: warning: ISO C90 forbids mixed declarations and code
In file included from /usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack/pack.h:116,
                 from /usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack.h:25,
                 from rbtrace.c:23:
/usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack/pack_template.h: In function 'msgpack_pack_float':
/usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack/pack_template.h:639: warning: ISO C90 forbids mixed declarations and code
/usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack/pack_template.h: In function 'msgpack_pack_double':
/usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack/pack_template.h:648: warning: ISO C90 forbids mixed declarations and code
In file included from /usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack.h:27,
                 from rbtrace.c:23:
/usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack/sbuffer.h: In function 'msgpack_sbuffer_write':
/usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/dst/include/msgpack/sbuffer.h:77: warning: ISO C90 forbids mixed declarations and code
rbtrace.c: In function 'rbtrace__send_event':
rbtrace.c:167: warning: ISO C90 forbids mixed declarations and code
rbtrace.c:170: warning: ISO C90 forbids mixed declarations and code
rbtrace.c:240: warning: ISO C90 forbids mixed declarations and code
rbtrace.c:251: warning: passing argument 5 of 'sendto' from incompatible pointer type
rbtrace.c: In function 'event_hook':
rbtrace.c:324: warning: ISO C90 forbids mixed declarations and code
rbtrace.c:340: warning: ISO C90 forbids mixed declarations and code
rbtrace.c:348: warning: comparison between signed and unsigned
rbtrace.c:297: warning: unused parameter 'data'
rbtrace.c: In function 'rbtracer_detach':
rbtrace.c:624: warning: ISO C90 forbids mixed declarations and code
rbtrace.c: In function 'rbtracer_add':
rbtrace.c:663: warning: ISO C90 forbids mixed declarations and code
rbtrace.c: In function 'ruby_teardown':
rbtrace.c:813: warning: unused parameter 'data'
rbtrace.c: In function 'rbtrace__process_event':
rbtrace.c:860: warning: ISO C90 forbids mixed declarations and code
rbtrace.c:886: warning: ISO C90 forbids mixed declarations and code
rbtrace.c:911: warning: ISO C90 forbids mixed declarations and code
rbtrace.c:925: warning: ISO C90 forbids mixed declarations and code
rbtrace.c:956: error: too few arguments to function 'setpgrp'
rbtrace.c:957: warning: ISO C90 forbids mixed declarations and code
rbtrace.c: In function 'sigurg':
rbtrace.c:1023: warning: ISO C90 forbids mixed declarations and code
rbtrace.c:1038: warning: ISO C90 forbids mixed declarations and code
rbtrace.c:1011: warning: unused parameter 'signal'
rbtrace.c: In function 'signal_handler_wrapper':
rbtrace.c:1060: warning: unused parameter 'arg'
rbtrace.c:1060: warning: unused parameter 'ctx'
*** Error code 1

Stop in /usr/home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext.

Gem files will remain installed in /home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1 for inspection.
Results logged to /home/discourse/.rvm/gems/ruby-2.0.0-p247/gems/rbtrace-0.4.1/ext/gem_make.out

---

Any solution, or do you need more information?

Thank you. :-)

**Comment by tmm1** [comment]
This was fixed in #24
