### ISSUE TITLE
timeout parameter ignored

### ISSUE THREAD

**Issue by dgobaud** [tmm1/rbtrace#32]
using timeout 3000 it fails after maybe 5-10 seconds.

 rbtrace -p 12304 --timeout 3000 -e 'Thread.new{require "objspace"; ObjectSpace::trace_object_allocations_start; GC.start(); ObjectSpace.dump_all(output: File.open("heap1.json", "w"))}.join'
*** run `sudo sysctl kernel.msgmnb=1048576` to prevent losing events (currently: 16384 bytes)
*** attached to process 12304
*** timed out waiting for eval response

**Comment by feifanzhou** [comment]
@dgobaud The `--timeout` parameter is a timeout for attaching to the process, not for `eval` responses. I ran into this issue, fixed it by editing the installed gem. 

Using `rbenv`, the file is at `~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rbtrace-0.4.6/lib/rbtrace/rbtracer.rb`. Line 148 (inside `def eval`) sets a timeout of 15 seconds, I bumped that number and restarted my server process.

**Comment by tmm1** [comment]
Could you open a PR that uses the --timeout value for both cases?

**Comment by tmm1** [comment]
Fixed in #38
