### ISSUE TITLE
Cannot install on Windows 10

### ISSUE THREAD

**Issue by wjdhamilton** [tmm1/rbtrace#46]
Hi,

Whilst trying to install rbrtace on windows 10 using gem install rbtrace I get the following error:

Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/RailsInstaller/Ruby2.1.0/bin/ruby
extconf.rb:6:in `sys': ./configure --disable-dependency-tracking --disable-shared --with-pic --prefix=C:/RailsInstaller/
Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rbtrace-0.4.7/ext/dst/ --libdir=C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/
rbtrace-0.4.7/ext/dst/lib failed, please report to https://github.com/tmm1/rbtrace/issues (RuntimeError)
        from extconf.rb:41:in `block (2 levels) in <main>'
        from extconf.rb:34:in `chdir'
        from extconf.rb:34:in `block in <main>'
        from extconf.rb:30:in `chdir'
        from extconf.rb:30:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rbtrace-0.4.7 for inspection.
Results logged to C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/rbtrace-0.4.7/gem_make.out

Running on ruby 2.1.5, rubygems 2.2.2, Windows 10

**Comment by zivhundert** [comment]
i've got the same error but i guess it's because rbtrace supported running on linux or mac osx only according to it release notes.

**Comment by wjdhamilton** [comment]
Yeah, that would explain it. I've moved on from Windows since then, however.
