### ISSUE TITLE
How come SIGURG is used?

### ISSUE THREAD

**Issue by ionelmc** [tmm1/rbtrace#53]
Hey, 

How come this tool uses SIGURG? This is a very strange signal to use. 

As I understood it, the kernel can use this signal for other things, if you use [fcntl in a specific way](http://linux.die.net/man/2/fcntl). Woulnd't this create a problem? Eg: make rbtrace read from a queue when there's nothing in it.

**Comment by tmm1** [comment]
This signal is used because it does not conflict with signals like SIGUSR
which are commonly used by web servers and other libraries.

SIGURG is also one of the few signals that is ignored by default, so your
program will not exit inadvertently if rbtrace is not setup correctly.

**Comment by ionelmc** [comment]
Interesting. Wouldn't sending SIGURG randomly to process make rbtrace misbehave?

After looking at http://man7.org/linux/man-pages/man7/signal.7.html it turns out that there are few more which are ignored by default: SIGPWR, SIGWINCH, SIGIO

**Comment by tmm1** [comment]
rbtrace should be fine even if it receives some stray signals.

**Comment by ionelmc** [comment]
Thanks, this is useful.
