### ISSUE TITLE
Ruby API rb_frame_method_id_and_class will be deprecated from Ruby 2.5

### ISSUE THREAD

**Issue by k0kubun** [tmm1/rbtrace#60]
https://github.com/ruby/ruby/commit/b6946d31fc201f6e6a5e046d58b69fa377bb76af

For Ruby 2.6+, we should remove its usage.

**Comment by tmm1** [comment]
Is there a replacement?

**Comment by k0kubun** [comment]
Unfortunately currently no replacement is exported.

The API's actual removal should come with its replacement. So let's close this for now until the new API is fixed. Sorry for early notification.
