### ISSUE TITLE
Can't install gem on OSX 10.5.8

### ISSUE THREAD

**Issue by gmoore** [tmm1/rbtrace#8]
Can't install the gem on my OSX laptop.  Details below.  Let me know if you need more info.

OSX 10.5.8
$ ruby -v
ruby 1.8.7 (2008-08-11 patchlevel 72) [i686-darwin9]

$ sudo gem install rbtrace
Building native extensions.  This could take a while...
ERROR:  Error installing rbtrace:
    ERROR: Failed to build gem native extension.

/opt/local/bin/ruby extconf.rb
  -- tar zxvf msgpack-0.5.4.tar.gz
  -- ./configure --disable-dependency-tracking --disable-shared --disable-cxx --with-pic --prefix=/opt/local/lib/ruby/gems/1.8/gems/rbtrace-0.3.12/ext/dst/
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/opt/local/bin/ruby
extconf.rb:6:in `sys': ./configure --disable-dependency-tracking --disable-shared --disable-cxx --with-pic --prefix=/opt/local/lib/ruby/gems/1.8/gems/rbtrace-0.3.12/ext/dst/ failed, please report to https://github.com/tmm1/rbtrace/issues (RuntimeError)
    from extconf.rb:35
    from extconf.rb:31:in`chdir'
    from extconf.rb:31
    from extconf.rb:27:in `chdir'
    from extconf.rb:27

**Comment by SamSaffron** [comment]
I am closing this, can not keep it open for all these years

**Comment by pdkproitf** [comment]
```
bundle update ffi
bundle update rbtrace
```
This works for me. I'm using Big Sur 11.2.
